# Generated by Django 4.2.8 on 2024-04-04 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alter_match_round_alter_round_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='match',
            name='round',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2_score',
        ),
        migrations.AddField(
            model_name='match',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.tournament'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.TextField(default=1, help_text='Enter team names, separating each one with a new line'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('single', 'Single Elimination'), ('double', 'Double Elimination')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
