# Generated by Django 4.2.8 on 2024-04-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_tournament_author_tournament_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='teams',
        ),
        migrations.AddField(
            model_name='tournament',
            name='team_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
