# Generated by Django 4.2.8 on 2024-04-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_match_round_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='score2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
