# Generated by Django 4.2.8 on 2024-04-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_tournament_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
