# Generated by Django 4.2.8 on 2024-04-18 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_alter_match_team1_alter_match_team2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 21, 38, 44, 383260)),
            preserve_default=False,
        ),
    ]
